openapi: 3.0.3
info:
  title: Teeinblue Print Partner API
  description: |
    Minimal REST API for print partners to sync catalogs with Teeinblue.
    Scope: **GET /catalogs** (list) and **GET /catalogs/{id}** (detail).
  version: 1.0.0

servers:
  - url: https://api.printer.com/v1
    description: Production server (example)

security:
  - bearerAuth: []

tags:
  - name: Catalogs
    description: Endpoints for listing and retrieving catalogs

paths:
  /catalogs:
    get:
      tags:
        - Catalogs
      summary: List catalogs
      description: Returns a paginated list of catalogs. Use `updated_at_min` for incremental sync.
      operationId: listCatalogs
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: per_page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - in: query
          name: search
          schema:
            type: string
            minLength: 2
          description: Search by catalog name.
        - in: query
          name: ids
          schema:
            type: string
          description: Comma separated list of catalog IDs to include.
        - in: query
          name: updated_at_min
          schema:
            type: string
            format: date-time
          description: Only return catalogs whose `updated_at` is >= this value (ISO 8601 UTC).
        - in: query
          name: locale
          schema:
            type: string
          description: Language for translatable fields (e.g., `vi`, `en`).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CatalogListItem'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
              example:
                data:
                  - id: 7
                    name: Unisex Standard T-Shirt
                    display_images:
                      - thumbnail: "https://example.com/thumb.jpg"
                        original: "https://example.com/original.jpg"
                    updated_at: "2025-08-19T10:20:00Z"
                pagination:
                  page: 1
                  per_page: 50
                  total: 1234
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/RateLimited'
        '500':
          $ref: '#/components/responses/InternalError'

  /catalogs/{id}:
    get:
      tags:
        - Catalogs
      summary: Catalog detail
      description: Returns full catalog details for a given ID.
      operationId: getCatalog
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
        - in: query
          name: locale
          schema:
            type: string
          description: Language for translatable fields (e.g., `vi`, `en`).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalog'
              example:
                id: 7
                name: Unisex Standard T-Shirt
                description: "<p>HTML mô tả...</p>"
                display_images:
                  - thumbnail: "https://example.com/thumb.jpg"
                    original: "https://example.com/original.jpg"
                print_areas:
                  - name: front
                    width: 4050
                    height: 4650
                    dpi: 300
                  - name: back
                    width: 4050
                    height: 4650
                    dpi: 300
                variants:
                  - size: S
                    color: Black
                    base_cost: "6.99"
                    availability: in_stock
                    weight: null
                  - size: S
                    color: Safety Pink
                    base_cost: "6.99"
                    availability: backorder
                    weight: null
                  - size: 5XL
                    color: Ice Grey
                    base_cost: "12.49"
                    availability: out_of_stock
                    weight: null
                updated_at: "2025-08-19T10:20:00Z"
        '404':
          $ref: '#/components/responses/NotFound'
        '410':
          description: Gone (catalog permanently removed)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'
    RateLimited:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'
    InternalError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'

  schemas:
    Pagination:
      type: object
      properties:
        page:
          type: integer
        per_page:
          type: integer
        total:
          type: integer
      required:
        - page
        - per_page
        - total

    Image:
      type: object
      properties:
        thumbnail:
          type: string
          format: uri
        original:
          type: string
          format: uri
      required:
        - thumbnail
        - original

    PrintArea:
      type: object
      properties:
        name:
          type: string
          enum: [front, back, left, right, custom]
        width:
          type: integer
        height:
          type: integer
        dpi:
          type: integer
          enum: [150, 300, 600]
      required:
        - name
        - width
        - height
        - dpi

    Variant:
      type: object
      properties:
        size:
          type: string
        color:
          type: string
        color_hex:
          type: string
          nullable: true
          pattern: "^#?[0-9A-Fa-f]{6}$"
        base_cost:
          type: string
          pattern: "^\\d+\\.\\d{2}$"
        availability:
          type: string
          enum: [in_stock, backorder, out_of_stock]
        weight:
          type: number
          nullable: true
      required:
        - size
        - color
        - base_cost
        - availability

    CatalogListItem:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        display_images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - name

    Catalog:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        display_images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        print_areas:
          type: array
          items:
            $ref: '#/components/schemas/PrintArea'
        variants:
          type: array
          items:
            $ref: '#/components/schemas/Variant'
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - description
        - display_images
        - print_areas
        - variants

    ErrorEnvelope:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            request_id:
              type: string
            details:
              type: object
              additionalProperties: true
          required:
            - code
            - message
      required:
        - error
