openapi: 3.1.0
required: true
schema: { type: integer, minimum: 1 }
- in: query
name: locale
schema: { type: string }
responses:
'200':
description: OK
content:
application/json:
schema:
$ref: '#/components/schemas/Catalog'
'404': { description: Not Found }
components:
schemas:
Pagination:
type: object
properties:
page: { type: integer }
per_page: { type: integer }
total: { type: integer }
CatalogListItem:
type: object
properties:
id: { type: integer }
name: { type: string }
display_images:
type: array
items:
$ref: '#/components/schemas/Image'
updated_at: { type: string, format: date-time }
Catalog:
type: object
properties:
id: { type: integer }
name: { type: string }
description: { type: string }
display_images:
type: array
items:
$ref: '#/components/schemas/Image'
print_areas:
type: array
items:
$ref: '#/components/schemas/PrintArea'
variants:
type: array
items:
$ref: '#/components/schemas/Variant'
updated_at: { type: string, format: date-time }
Image:
type: object
properties:
thumbnail: { type: string, format: uri }
original: { type: string, format: uri }
PrintArea:
type: object
properties:
name: { type: string, enum: [front, back, left, right, custom] }
width: { type: integer }
height: { type: integer }
dpi: { type: integer, enum: [150, 300, 600] }
Variant:
type: object
properties:
size: { type: string }
color: { type: string }
color_hex: { type: [string, 'null'] }
base_cost: { type: string }
availability: { type: string, enum: [in_stock, backorder, out_of_stock] }
weight: { type: [number, 'null'] }
